spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sns
    username: jyuka
    password: 1234
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    # OSIV 끔
    # 참고 URL : https://ykh6242.tistory.com/entry/JPA-OSIVOpen-Session-In-View%EC%99%80-%EC%84%B1%EB%8A%A5-%EC%B5%9C%EC%A0%81%ED%99%94
    open-in-view: false
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: MANUAL
    consumer:
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: "*"
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      notification: alarm

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

jwt:
  secret-key: Task :prepareKotlinBuildScriptModel UP-TO-DATE
  # 30 days : 24 * 60 * 60 * 30 (ms 단위)
  token.expired-time-ms: 2592000000