spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sns
    username: jyuka
    password: 1234
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    # OSIV 끔
    # 참고 URL : https://ykh6242.tistory.com/entry/JPA-OSIVOpen-Session-In-View%EC%99%80-%EC%84%B1%EB%8A%A5-%EC%B5%9C%EC%A0%81%ED%99%94
    open-in-view: false
  redis:
    host: localhost
    port: 6379

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

jwt:
  secret-key: Task :prepareKotlinBuildScriptModel UP-TO-DATE
  # 30 days : 24 * 60 * 60 * 30 (ms 단위)
  token.expired-time-ms: 2592000000